# variables
@baseUrl = http://brq.test/api

###

# Login
# @name login
POST {{baseUrl}}/login
Accept: application/json
Content-Type: application/json

{
  "email": "reichel.aurelia@example.net",
  "password": "password"
}

###

@token = {{login.response.body.access_token}}
@userId = {{login.response.body.user.id}}

###

# Get user profile
GET {{baseUrl}}/user
Authorization: Bearer {{token}}
Accept: application/json

###

# Get all transactions
GET {{baseUrl}}/transactions
Authorization: Bearer {{token}}
Accept: application/json

###

# Get a specific transaction
GET {{baseUrl}}/transactions/3
Authorization: Bearer {{token}}
Accept: application/json

###

# Create a new transaction
POST {{baseUrl}}/transactions
Authorization: Bearer {{token}}
Accept: application/json
Content-Type: application/json

{
  "amount": 1009.00,
  "document": "1234567890",
  "currency": "USD",
  "created_at": "2023-10-01T01:00:00Z"
}


###
# Filter transactions by date
GET {{baseUrl}}/transactions?start_date=invalid&end_date=invalid
Authorization: Bearer {{token}}
Accept: application/json

